= Standard Platform League

== Overview
The standard platform league (SPL) is part of the international RoboCup. The RoboCup's aim is to foster education of students in the area of robotics. The international RoboCup is basically divided into two major branches, namely the RoboCupJunior (for students from 14 to 19 years of age) and the RoboCupMajor (for students above 19 years of age).

On a lower level the RoboCup is divided into several leagues which emphasize different areas of robotics. One can find leagues for industrial robots, humanoid robotics, robo soccer, and many more. The standard platform league is one of the four robo soccer leagues. The common goal of all the robo soccer leagues is to build robots which can play a soccer match against the FIFA world champion of 2050.

The main teams of the league are

- https://www.b-human.de/index-de.html[*BHuman*,role=black] +
- https://hulks.de/[*HULKS*,role=black] +
- https://www.htwk-leipzig.de/startseite/[*HTWK Leibzig*,role=black]
- https://www.engineering.unsw.edu.au/computer-science-engineering/student-life/student-projects/robocup[*rUnswift*,role=black]


== Goals
The goals of the standard platform league is the development of software for autonomous robots for playing soccer. A very special feature of the SPL is that all robots taking part are of the same manifacturer (NAOs from SoftBank robotics) and the competition is focused on the quality of the software only.

It offers special challenges for interaction between autonomous systems, computer vision, motion, etc. In the future parts of speech recognition and natural language processing are planned to be incorporated into this league.

== Basic Rules
As of writing of this text the basic rules can be summarized as follows:

- The soccer field has a dimension of 9 x 6 meters
- One team consists of five robots, one keeper and four field players
- The robots have to play by themselves. There is no human interaction allowed
- A match is controlled by three human referees but the robots get commands from the referees via the so called game controller

The rules are updated each year and the challenge became more complex during the last years. A more detailed explanation of the current rules can be found on the  https://spl.robocup.org/wp-content/uploads/downloads/Rules2019.pdf[*SPL website*,role=black].
